// Copyright 2026 Simon Sagmeister
// This file was generated by: Open-Car-Dynamics/ros2/open_car_dynamics_ros2/tools/create_combinations.py
#include "open_car_dynamics_ros2/components.hpp"

OCD_NODE_COMPONENT(
  WheelTorque__PT1__DoubleTrack__MF52__DefaultAerodynamics,
  tam::sim::drivetrain::DrivetrainWheelTorqueModel,
  tam::sim::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::sim::steering_actuator::PT1SteeringActuatorModel,
  tam::sim::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::sim::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::sim::aerodynamics::DefaultAerodynamicsModel, tam::sim::tire_models::MF52)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__DoubleTrack__Linear__DefaultAerodynamics,
  tam::sim::drivetrain::DrivetrainWheelTorqueModel,
  tam::sim::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::sim::steering_actuator::PT1SteeringActuatorModel,
  tam::sim::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::sim::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::sim::aerodynamics::DefaultAerodynamicsModel, tam::sim::tire_models::Linear)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__DoubleTrack__MF_Simple__DefaultAerodynamics,
  tam::sim::drivetrain::DrivetrainWheelTorqueModel,
  tam::sim::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::sim::steering_actuator::PT1SteeringActuatorModel,
  tam::sim::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::sim::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::sim::aerodynamics::DefaultAerodynamicsModel, tam::sim::tire_models::MF_Simple)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__DoubleTrack__MF_Simple_Extended__DefaultAerodynamics,
  tam::sim::drivetrain::DrivetrainWheelTorqueModel,
  tam::sim::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::sim::steering_actuator::PT1SteeringActuatorModel,
  tam::sim::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::sim::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::sim::aerodynamics::DefaultAerodynamicsModel, tam::sim::tire_models::MF_Simple_Extended)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__DoubleTrack__MF52__RideHeightAerodynamics,
  tam::sim::drivetrain::DrivetrainWheelTorqueModel,
  tam::sim::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::sim::steering_actuator::PT1SteeringActuatorModel,
  tam::sim::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::sim::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::sim::aerodynamics::RideHeightAerodynamicsModel, tam::sim::tire_models::MF52)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__DoubleTrack__Linear__RideHeightAerodynamics,
  tam::sim::drivetrain::DrivetrainWheelTorqueModel,
  tam::sim::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::sim::steering_actuator::PT1SteeringActuatorModel,
  tam::sim::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::sim::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::sim::aerodynamics::RideHeightAerodynamicsModel, tam::sim::tire_models::Linear)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__DoubleTrack__MF_Simple__RideHeightAerodynamics,
  tam::sim::drivetrain::DrivetrainWheelTorqueModel,
  tam::sim::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::sim::steering_actuator::PT1SteeringActuatorModel,
  tam::sim::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::sim::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::sim::aerodynamics::RideHeightAerodynamicsModel, tam::sim::tire_models::MF_Simple)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__DoubleTrack__MF_Simple_Extended__RideHeightAerodynamics,
  tam::sim::drivetrain::DrivetrainWheelTorqueModel,
  tam::sim::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::sim::steering_actuator::PT1SteeringActuatorModel,
  tam::sim::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::sim::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::sim::aerodynamics::RideHeightAerodynamicsModel, tam::sim::tire_models::MF_Simple_Extended)

OCD_NODE_COMPONENT(
  Fx__PT1__DoubleTrack__MF52__DefaultAerodynamics,
  tam::sim::drivetrain::DrivetrainFxModel,
  tam::sim::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::sim::steering_actuator::PT1SteeringActuatorModel,
  tam::sim::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::sim::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::sim::aerodynamics::DefaultAerodynamicsModel, tam::sim::tire_models::MF52)

OCD_NODE_COMPONENT(
  Fx__PT1__DoubleTrack__Linear__DefaultAerodynamics,
  tam::sim::drivetrain::DrivetrainFxModel,
  tam::sim::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::sim::steering_actuator::PT1SteeringActuatorModel,
  tam::sim::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::sim::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::sim::aerodynamics::DefaultAerodynamicsModel, tam::sim::tire_models::Linear)

OCD_NODE_COMPONENT(
  Fx__PT1__DoubleTrack__MF_Simple__DefaultAerodynamics,
  tam::sim::drivetrain::DrivetrainFxModel,
  tam::sim::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::sim::steering_actuator::PT1SteeringActuatorModel,
  tam::sim::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::sim::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::sim::aerodynamics::DefaultAerodynamicsModel, tam::sim::tire_models::MF_Simple)

OCD_NODE_COMPONENT(
  Fx__PT1__DoubleTrack__MF_Simple_Extended__DefaultAerodynamics,
  tam::sim::drivetrain::DrivetrainFxModel,
  tam::sim::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::sim::steering_actuator::PT1SteeringActuatorModel,
  tam::sim::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::sim::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::sim::aerodynamics::DefaultAerodynamicsModel, tam::sim::tire_models::MF_Simple_Extended)

OCD_NODE_COMPONENT(
  Fx__PT1__DoubleTrack__MF52__RideHeightAerodynamics,
  tam::sim::drivetrain::DrivetrainFxModel,
  tam::sim::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::sim::steering_actuator::PT1SteeringActuatorModel,
  tam::sim::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::sim::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::sim::aerodynamics::RideHeightAerodynamicsModel, tam::sim::tire_models::MF52)

OCD_NODE_COMPONENT(
  Fx__PT1__DoubleTrack__Linear__RideHeightAerodynamics,
  tam::sim::drivetrain::DrivetrainFxModel,
  tam::sim::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::sim::steering_actuator::PT1SteeringActuatorModel,
  tam::sim::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::sim::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::sim::aerodynamics::RideHeightAerodynamicsModel, tam::sim::tire_models::Linear)

OCD_NODE_COMPONENT(
  Fx__PT1__DoubleTrack__MF_Simple__RideHeightAerodynamics,
  tam::sim::drivetrain::DrivetrainFxModel,
  tam::sim::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::sim::steering_actuator::PT1SteeringActuatorModel,
  tam::sim::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::sim::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::sim::aerodynamics::RideHeightAerodynamicsModel, tam::sim::tire_models::MF_Simple)

OCD_NODE_COMPONENT(
  Fx__PT1__DoubleTrack__MF_Simple_Extended__RideHeightAerodynamics,
  tam::sim::drivetrain::DrivetrainFxModel,
  tam::sim::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::sim::steering_actuator::PT1SteeringActuatorModel,
  tam::sim::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::sim::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::sim::aerodynamics::RideHeightAerodynamicsModel, tam::sim::tire_models::MF_Simple_Extended)

